# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: /packages/blogpress
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: /packages/create-theme
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: /packages/theme
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: /packages/vitepress-plugin-pagefind
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directory: /packages/vitepress-plugin-rss
    schedule:
      interval: daily
      time: '04:00'
    open-pull-requests-limit: 20
