name: Create Release Tag

on:
  push:
    tags:
      - 'v*' # Push events to matching @sugarat/theme*

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Release for Tag
        id: release_tag
        uses: ncipollo/release-action@v1.14.0
        with:
          generateReleaseNotes: true
          draft: true
          body: |
            > Please refer to [CHANGELOG.md](https://github.com/cnjimbo/cnjimbo.github.io/blob/master/packages/theme/CHANGELOG.md) for details.
