name: Auto update npm dependencies
on:
  schedule:
    # runs monthly At 00:01 on day-of-month 1
    - cron: '1 0 1 * *'
  workflow_dispatch:

jobs:
  auto-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # 默认只拉取分支最近一次的 commit，可能会导致一些文章的 GitInfo 变量无法获取，设为 0 代表拉取所有分支所有提交
          fetch-depth: 0
      - name: Git Configuration
        # 2、配置 Git
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false
      - name: Setup PNPM
        # 3、安装 PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Setup Node
        # 4、安装 Node 环境
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 21
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install Dependencies
        run: |
          pnpm i --no-frozen-lockfile
          # if [ -f pnpm-lock.yaml ]; then
          #   pnpm install --frozen-lockfile
          # else
          #   pnpm install
          # fi

      - name: Run auto dependency update
        uses: romoh/dependencies-autoupdate@v1.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          update-command: '''pnpm up -r -w && pnpm buildlib && pnpm build'''
          # update-path: "''" #optional
          pr-branch: master
