name: Dependabatch updates

on:
  workflow_dispatch:
  schedule:
    # * is special in YAML.  This runs at 4:45 am on Sundays.
    - cron: '45 4 * * 0'

jobs:
  update-deps:
    name: Update dependencies
    runs-on: [ubuntu-latest]

    steps:
      # - name: Update python deps
      #   uses: boozallen/dependency-update-action@v1
      #   with:
      #     dotcom_token: ${{ secrets.GITHUB_TOKEN }}
      #     ghe_token: ${{ secrets.GHE_TOKEN }}
      #     ghe_hostname: ${{ secrets.GHE_HOSTNAME }}
      #     repo_name: ${{ github.repository }}
      #     directory: "/"
      #     package_manager: "pip"
      #     batch_size: "20"

      - name: Update JavaScript deps
        uses: boozallen/dependency-update-action@v1
        with:
          dotcom_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.repository }}
          directory: /
          package_manager: npm_and_yarn
          batch_size: '10'

      - name: Update GitHub Actions
        uses: boozallen/dependency-update-action@v1
        with:
          dotcom_token: ${{ secrets.GITHUB_TOKEN }}
          repo_name: ${{ github.repository }}
          directory: /
          package_manager: github_actions
          batch_size: '5'
