name: Deploy

on:
  push:
    branches:
      - docs-deploy

jobs:
  github-branch-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Use node
        uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm docs:build

      - name: Update the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist

  gitee-branch-sync:
    needs: [github-branch-update]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Sync branches to GitHube
        uses: peiyanlu/git-sync-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        with:
          source-repo: git@github.com:peiyanlu/vite-press.git
          destination-repo: git@gitee.com:peiyanlu/vite-press.git
          destination-branch: gh-pages

  gitee-pages-deploy:
    needs: [gitee-branch-sync]
    runs-on: ubuntu-latest
    steps:
      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          gitee-username: peiyanlu
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          gitee-repo: peiyanlu/vite-press
          branch: gh-pages

  search-algolia:
    needs: [github-branch-update]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Push indices to Algolia
        uses: peiyanlu/algolia-docsearch-action@master
        with:
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_config_file: algolia.config.json
